### ISSUE TITLE
Does not support IBM LSF scheduler?

### ISSUE THREAD

**Issue by ieee8023** [SMART-Lab/smartdispatch#163]
I get this error on a cluster with the IBM LSF scheduler (http://wiki.umassrc.org/wiki/index.php/Main_Page)

```
$ smart-dispatch 
WARNING:root:Cluster does not support flock! Falling back to folder lock.
qstat: illegal option -- B
Usage: qstat [-l] [-m] [-x] [-a] [-u user-name] [queue-name ...]
Traceback (most recent call last):
  File ".local/bin/smart-dispatch", line 23, in <module>
    CLUSTER_NAME = utils.detect_cluster()
  File "/home/jc93b/.local/lib/python2.7/site-packages/smartdispatch/utils.py", line 120, in detect_cluster
    server_name = output.split('\n')[2].split(' ')[0]
IndexError: list index out of range
```

**Comment by mgermain** [comment]
It only supports PBS based clusters, but it should not be that hard to
extend it.
