### ISSUE TITLE
utils.slugger chokes on unicode

### ISSUE THREAD

**Issue by samuelstjean** [SMART-Lab/smartdispatch#76]
Apparently, having a unicode encoded file works, but if it contains unicode caracters it doesn't.

```
stjeans1 ~ $ smart_dispatch.py -x -f file.txt -q qwork@mp2 -t 1:10:00:00 launch 
Traceback (most recent call last):
  File "/home/stjeans1/.local/bin/smart_dispatch.py", line 180, in <module>
    main()
  File "/home/stjeans1/.local/bin/smart_dispatch.py", line 74, in main
    log_filename = os.path.join(path_job_logs, smartdispatch.generate_name_from_command(command, max_length_arg=30))
  File "/home/stjeans1/.local/lib/python2.7/site-packages/smartdispatch/smartdispatch.py", line 41, in generate_name_from_command
    name = '_'.join([utils.slugify(argvalue)[max_length_arg:] for argvalue in command.split()])
  File "/home/stjeans1/.local/lib/python2.7/site-packages/smartdispatch/utils.py", line 33, in slugify
    value = unicodedata.normalize('NFKD', unicode(value)).encode('ascii', 'ignore').decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

where file .txt contains
echo "éé"

**Comment by mgermain** [comment]
Also fails directly from the command line.

```
germainm@mp2-ip08 ~$ smart_dispatch.py -q qtest@mp2 launch echo "éé"
Traceback (most recent call last):
  File "/home/larochel_group/.local/bin/smart_dispatch.py", line 199, in <module>
    main()
  File "/home/larochel_group/.local/bin/smart_dispatch.py", line 43, in main
    jobname = smartdispatch.generate_name_from_command(command, max_length=235)
  File "/home/larochel_group/.local/lib/python2.7/site-packages/smartdispatch/smartdispatch.py", line 39, in generate_name_from_command
    name += '_'.join([utils.slugify(argvalue)[max_length_arg:] for argvalue in command.split()])
  File "/home/larochel_group/.local/lib/python2.7/site-packages/smartdispatch/utils.py", line 60, in slugify
    value = unicodedata.normalize('NFKD', unicode(value)).encode('ascii', 'ignore').decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```
